[package]
name = "speclink-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "speclink"
path = "src/main.rs"

[dependencies]
speclink-core = { path = "../speclink-core" }
speclink-fs = { path = "../speclink-fs" }
speclink-remote = { path = "../speclink-remote" }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
clap.workspace = true
clap_complete = "4"

[dev-dependencies]
tiny_http = "0.12"
chrono.workspace = true
